### ISSUE TITLE
.Any() in WHERE-statement results in no optimization

### ISSUE THREAD

**Issue by MBerantzino** [Thorium/Linq.Expression.Optimizer#9]
### Description

A simple Entity Framework query with a Any(...) statement in the WHERE statement results in no optimizations being performed. Excluding the Any(...) part results in optimizations being performed.

### Repro steps

Have the simple EF query:

var onlyX = true;

var query =
(
  from st in Context.S.AsExpandable()
  join la in Context.L on st.LId equals la.LId
  where
    (
      !onlyX ||
      (onlyX && la.LId == 3)
    ) &&
    Context.SL.Any(sl => sl.SId== st.SId && sl.UId == null)
  select new
  {
    st.SId,
    la.LId
  }
);

### Expected behavior

Expected the following query

var query =
(
  from st in Context.S.AsExpandable()
  join la in Context.L on st.LId equals la.LId
  where
    (
      la.LId == 3
    ) &&
    Context.SL.Any(sl => sl.SId== st.SId && sl.UId == null)
  select new
  {
    st.SId,
    la.LId
  }
);

### Actual behavior

The query is left un-optimized.

Removing the "Context.SL.Any(sl => sl.SId== st.SId && sl.UId == null)" statement from the query causes the query to be optimized.

### Known workarounds

None.

### Related information 

Linq.Expression.Optimizer NuGet package 1.0.12 (latest at the time of writing).
LinqKit.EntityFramework NuGet package v1.1.16 (latest at the time of writing).

**Comment by Thorium** [comment]
I'll check this later, I expect the reason is that Context.SL.Any(...) is kind of unknown method that could contain side-effects easily. As nothing states clearly it's a linq-call, you could override the .Any()-method with your custome logic.

Now the interesting question is, should we partially-optimize the expressions that we don't recognize fully, and also the nested expressions, like the Any-parameter-expression here.

**Comment by Thorium** [comment]
As a workaround, you could write your where-condition with a normal join instead of Any, something like `join sl in Context.SL on (sl.SId == st.SId && sl.UId == null)` or
`join sl in Context.SL on ((new Tuple(sl.SId, sl.UId)) == (new Tuple(st.SId, null)))` (I've not written C# for years but I expect it has to support something like that).

**Comment by MBerantzino** [comment]
I could indeed perform a normal join - but there are technical reasons that this is not desirable in this particular case.

This is also just the most basic example I could come up with - in my code the logic is much more complex - where Any() is the only option.

**Comment by Thorium** [comment]
I was checking this. Currently this optimizer doesn't do the optimization at runtime, instead the user asks the expression tree to be optimized. So we don't do any wrap-and-optimize-later-hacks.

Because the LINQ seems to be quite complex, instead of .NET running the LINQ the typical way, .NET actually wraps the expression tree to a wrapper class called WhereSelectEnumerableIterator for waiting some kind of execution-time-evaluation with some internal caching:
https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,8bf16962931637d3,references 

So then there is only a ConstantExpression of a constructor, instead of the real expression tree.
WhereSelectEnumerableIterator is internal class visible to System.Linq only. It has internal field called "source", which holds the LINQ-tree that should be optimised. That field can be read with reflection (reflection is not optimal, but not many options here), and optimised and written back to the original class.

So this is now released in NuGet version 1.0.13
Please test and tell if this did help your case or not.
